"""
Demo script showing current QuantEvolve features
This demonstrates what's been implemented so far
"""

import sys
import os

# Add src to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))

from utils.config_loader import load_config
from utils.logger import setup_logger, get_logger
from utils.llm_client import create_llm_client, LLMEnsemble
from core.feature_map import create_feature_map_from_config, Strategy
from core.evolutionary_database import EvolutionaryDatabase
from agents.data_agent import DataAgent

import numpy as np


def main():
    """Demo current features"""

    # 1. Setup
    print("=" * 80)
    print("QuantEvolve - Current Features Demo")
    print("=" * 80)
    print()

    # Load configuration
    print("1. Loading configuration...")
    config = load_config()
    print(f"   ✓ Loaded config from: config/default_config.yaml")
    print(f"   - Evolution: {config.get('evolution.num_generations')} generations, "
          f"{config.get('evolution.num_islands')} islands")
    print(f"   - Feature Map: {len(config.get('feature_map.dimensions'))} dimensions")
    print()

    # Setup logger
    print("2. Setting up logger...")
    setup_logger(
        log_dir=config.get('logs_path', './logs'),
        level=config.get('logging.level', 'INFO')
    )
    logger = get_logger()
    print("   ✓ Logger configured")
    print()

    # Create LLM client
    print("3. Initializing LLM client (OpenRouter)...")
    llm_config = config.get('llm', {})
    llm_client = create_llm_client(llm_config)
    llm_ensemble = LLMEnsemble(llm_client)
    print(f"   ✓ Connected to OpenRouter")
    print(f"   - Small Model: {llm_client.small_model}")
    print(f"   - Large Model: {llm_client.large_model}")
    print()

    # Create feature map
    print("4. Creating feature map...")
    feature_map = create_feature_map_from_config(config.raw)
    print(f"   ✓ Feature map created")
    print(f"   - Shape: {feature_map.archive.shape}")
    print(f"   - Total cells: {np.prod(feature_map.archive.shape)}")
    print(f"   - Dimensions:")
    for dim in feature_map.dimensions:
        print(f"     • {dim.name} ({dim.type}): {dim.bins} bins")
    print()

    # Create evolutionary database
    print("5. Creating evolutionary database...")
    categories = config.get('strategy_categories', [])
    num_islands = len(categories) + 1  # +1 for benchmark
    evol_db = EvolutionaryDatabase(
        feature_map=feature_map,
        num_islands=num_islands,
        categories=categories
    )
    print(f"   ✓ Evolutionary database created")
    print(f"   - Islands: {num_islands}")
    print(f"   - Categories: {', '.join(categories)}")
    print()

    # Demo: Create sample strategies
    print("6. Demo: Creating sample strategies...")
    print("   (In full system, these would be generated by Data Agent)")
    print()

    sample_strategies = []
    for i, category in enumerate(categories[:3]):  # Just first 3 for demo
        print(f"   Creating sample strategy for: {category}")
        strategy = Strategy(
            hypothesis=f"Sample {category} strategy for demonstration",
            code=f"# Placeholder code for {category}\npass",
            metrics={
                'sharpe_ratio': np.random.uniform(0.5, 2.0),
                'sortino_ratio': np.random.uniform(0.5, 2.0),
                'information_ratio': np.random.uniform(-0.5, 1.0),
                'total_return': np.random.uniform(0, 200),
                'max_drawdown': -np.random.uniform(10, 40),
                'trading_frequency': np.random.randint(10, 500),
                'strategy_category_bin': 1 << i  # Binary encoding
            },
            analysis=f"Sample analysis for {category} strategy",
            generation=0,
            island_id=i
        )
        sample_strategies.append(strategy)
        print(f"     ✓ Strategy created (Score: {strategy.combined_score:.3f})")

    # Add to feature map
    print()
    print("7. Adding strategies to feature map...")
    for strategy in sample_strategies:
        added = feature_map.add(strategy)
        status = "Added" if added else "Rejected"
        print(f"   - {strategy.island_id}: {status} (Score: {strategy.combined_score:.3f})")

    print()
    stats = feature_map.get_statistics()
    print(f"   Feature Map Statistics:")
    print(f"   - Strategies: {stats['num_strategies']}")
    print(f"   - Coverage: {stats['coverage']*100:.2f}%")
    print(f"   - Mean Score: {stats.get('mean_score', 0):.3f}")
    print(f"   - Max Score: {stats.get('max_score', 0):.3f}")
    print()

    # Demo: Parent and cousin sampling
    print("8. Demo: Parent and Cousin Sampling")
    print("   (Initializing database with sample strategies)")

    # Initialize islands with sample strategies
    evol_db.initialize_islands(sample_strategies)

    # Sample parent
    parent = evol_db.sample_parent(island_id=0, alpha=0.5)
    if parent:
        print(f"   ✓ Sampled parent from island 0:")
        print(f"     - Strategy ID: {parent.strategy_id}")
        print(f"     - Score: {parent.combined_score:.3f}")
        print(f"     - Feature Vector: {parent.feature_vector}")

        # Sample cousins
        cousins = evol_db.sample_cousins(
            parent=parent,
            island_id=0,
            num_best=2,
            num_diverse=2,
            num_random=1
        )
        print(f"   ✓ Sampled {len(cousins)} cousin strategies")
    print()

    # Demo: Database statistics
    print("9. Evolutionary Database Statistics:")
    db_stats = evol_db.get_statistics()
    print(f"   - Generation: {db_stats['generation']}")
    print(f"   - Total Strategies: {db_stats['total_strategies']}")
    print(f"   - Strategies on Map: {db_stats['total_on_map']}")
    print(f"   - Rejected: {db_stats['total_rejected']}")
    print()
    print("   Island Statistics:")
    for island_stat in db_stats['islands'][:3]:  # First 3 islands
        print(f"     Island {island_stat['id']} ({island_stat['category']}):")
        print(f"       - Population: {island_stat['population_size']}")
        print(f"       - On Map: {island_stat['map_size']}")
        if 'max_score' in island_stat:
            print(f"       - Best Score: {island_stat['max_score']:.3f}")
    print()

    # Demo: Data Agent (commented out - requires LLM call)
    print("10. Data Agent Capability")
    print("    The Data Agent can:")
    print("    - Analyze data directories and detect schema")
    print("    - Generate Data Schema Prompts for strategies")
    print("    - Create seed strategies for each category")
    print("    - Generate benchmark strategies")
    print()
    print("    To test Data Agent with real LLM:")
    print("    ```python")
    print("    data_agent = DataAgent(llm_ensemble)")
    print("    schema = data_agent.analyze_data(")
    print("        data_dir='./data/raw',")
    print("        assets=['AAPL', 'NVDA', 'AMZN'],")
    print("        asset_type='equities'")
    print("    )")
    print("    seeds = data_agent.generate_all_seed_strategies(categories)")
    print("    ```")
    print()

    # Summary
    print("=" * 80)
    print("Summary: Current Implementation Status")
    print("=" * 80)
    print()
    print("✅ Completed:")
    print("   • Configuration system (YAML + env vars)")
    print("   • Logging infrastructure")
    print("   • OpenRouter LLM client (dual-model ensemble)")
    print("   • Feature Map (MAP-Elites quality-diversity)")
    print("   • Evolutionary Database (island model)")
    print("   • Parent and cousin sampling strategies")
    print("   • Data Agent (schema analysis + seed generation)")
    print("   • Comprehensive agent prompts")
    print()
    print("🚧 In Progress:")
    print("   • Research Agent (hypothesis generation)")
    print()
    print("📋 Next Steps:")
    print("   • Coding Team (strategy implementation)")
    print("   • Evaluation Team (analysis + insights)")
    print("   • Zipline backtesting integration")
    print("   • Main evolution loop")
    print("   • Data preparation utilities")
    print("   • Visualization tools")
    print()
    print("Current Implementation: ~35% complete")
    print()
    print("For detailed status, see: IMPLEMENTATION_STATUS.md")
    print("=" * 80)


if __name__ == "__main__":
    main()
