#!/usr/bin/env python3
"""
Export the best strategy as a standalone Python module
"""

import sys
import os
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

import pickle
from datetime import datetime


def export_strategy(results_dir="results/final", output_dir="exported_strategies"):
    """Export the best strategy as a standalone Python file"""

    # Load database
    db_path = Path(results_dir) / "evolutionary_database.pkl"
    with open(db_path, 'rb') as f:
        db = pickle.load(f)

    # Get all strategies and sort by combined score
    all_strategies = db.feature_map.get_all_strategies()
    all_strategies.sort(key=lambda s: s.combined_score, reverse=True)

    if not all_strategies:
        print("No strategies found!")
        return

    best_strategy = all_strategies[0]

    # Create output directory
    output_path = Path(output_dir)
    output_path.mkdir(exist_ok=True)

    # Generate standalone strategy file
    strategy_file = output_path / f"{best_strategy.strategy_id}.py"

    with open(strategy_file, 'w') as f:
        f.write('"""\n')
        f.write(f"Trading Strategy: {best_strategy.strategy_id}\n")
        f.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"Generation: {best_strategy.generation}\n")
        f.write(f"Combined Score: {best_strategy.combined_score:.3f}\n")
        f.write("\n")
        f.write("Performance Metrics:\n")
        for metric, value in best_strategy.metrics.items():
            if isinstance(value, float):
                f.write(f"  {metric}: {value:.3f}\n")
            else:
                f.write(f"  {metric}: {value}\n")
        f.write("\n")
        f.write("HYPOTHESIS:\n")
        f.write("-" * 80 + "\n")
        f.write(best_strategy.hypothesis)
        f.write("\n")
        f.write('"""\n\n')

        f.write("import pandas as pd\n")
        f.write("import numpy as np\n\n")

        f.write("# Strategy Code (auto-generated by QuantEvolve)\n")
        f.write(best_strategy.code)
        f.write("\n\n")

        f.write("if __name__ == '__main__':\n")
        f.write("    # Example usage\n")
        f.write("    print('Strategy loaded successfully!')\n")
        f.write(f"    print('Strategy ID: {best_strategy.strategy_id}')\n")
        sharpe = best_strategy.metrics.get('sharpe_ratio', 0)
        f.write(f"    print('Sharpe Ratio: {sharpe:.3f}')\n")

    print(f"✓ Strategy exported to: {strategy_file}")
    print(f"\nStrategy Details:")
    print(f"  ID: {best_strategy.strategy_id}")
    print(f"  Generation: {best_strategy.generation}")
    print(f"  Combined Score: {best_strategy.combined_score:.3f}")
    print(f"  Sharpe Ratio: {best_strategy.metrics.get('sharpe_ratio', 0):.3f}")
    print(f"  Total Return: {best_strategy.metrics.get('total_return', 0):.2f}%")

    # Export summary of top 10
    summary_file = output_path / "top_10_strategies_summary.txt"
    with open(summary_file, 'w') as f:
        f.write("=" * 80 + "\n")
        f.write("TOP 10 STRATEGIES FROM EVOLUTION\n")
        f.write("=" * 80 + "\n")
        f.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"Total Generations: {db.current_generation}\n")
        f.write("\n")

        for i, strategy in enumerate(all_strategies[:10], 1):
            f.write(f"\n{i}. Strategy {strategy.strategy_id}\n")
            f.write(f"   Generation: {strategy.generation}\n")
            f.write(f"   Combined Score: {strategy.combined_score:.3f}\n")
            f.write(f"   Sharpe Ratio: {strategy.metrics.get('sharpe_ratio', 0):.3f}\n")
            f.write(f"   Total Return: {strategy.metrics.get('total_return', 0):.2f}%\n")
            f.write(f"   Max Drawdown: {strategy.metrics.get('max_drawdown', 0):.2f}%\n")
            f.write("\n")

    print(f"✓ Top 10 summary exported to: {summary_file}")

    # Export the entire database info
    info_file = output_path / "model_info.txt"
    with open(info_file, 'w') as f:
        f.write("=" * 80 + "\n")
        f.write("QUANTEVOLVE MODEL INFORMATION\n")
        f.write("=" * 80 + "\n")
        f.write(f"Exported: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write("\n")
        f.write(f"Total Generations Evolved: {db.current_generation}\n")
        f.write(f"Number of Islands: {len(db.islands)}\n")
        f.write(f"Total Strategies in Feature Map: {len(all_strategies)}\n")
        f.write(f"Insights Collected: {len(db.insights)}\n")
        f.write("\n")
        f.write("Island Categories:\n")
        for i, island in enumerate(db.islands):
            f.write(f"  Island {i}: {island.category}\n")
        f.write("\n")
        f.write("Best Strategy:\n")
        f.write(f"  ID: {best_strategy.strategy_id}\n")
        f.write(f"  Generation: {best_strategy.generation}\n")
        f.write(f"  Score: {best_strategy.combined_score:.3f}\n")
        f.write("\n")
        f.write("=" * 80 + "\n")
        f.write("To use this model:\n")
        f.write("1. Load the strategy from the exported .py file\n")
        f.write("2. Call generate_signals(data) with OHLCV DataFrame\n")
        f.write("3. Use returned signals (-1, 0, 1) for trading\n")
        f.write("=" * 80 + "\n")

    print(f"✓ Model info exported to: {info_file}")
    print(f"\nAll files saved to: {output_path}/")


if __name__ == "__main__":
    export_strategy()
